### ISSUE TITLE
Markdown Support

### ISSUE THREAD

**Issue by boogah** [ekmartin/unicode-style#5]
First, I really appreciate this tool and look forward to seeing what else you do with it!

If I might make a feature request, it'd be nice if you could find a way to support [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) in the editor. That way, people could wrap their text in all of the requisite asterisks, underscores, etc. and get their formatted output without having to break their stride by reaching for their mouse.

Thanks for your time!

**Comment by ekmartin** [comment]
While this would be a cool idea I think it would be a bit out of scope for this project. Implementing something like a button that would take a full markdown document and then styling that would be doable, but I don't think it would be a very good user experience. The interesting thing to do would be to try to convert markdown on the fly, e.g. changing `**bold**` to **bold** when the last asterisk lands, but that would also be pretty complex to implement.

Maybe this could be useful as a command-line tool instead? It would take a full markdown document, parse it, and output a styled version. The implementation could call something like [applyStyles](https://github.com/ekmartin/unicode-style/blob/2952f520a2c2811e3dac96946766e49802b0a9bc/src/transform.js#L222) for each node in the tree.
