### ISSUE TITLE
pseudocode

### ISSUE THREAD

**Issue by bAndie91** [ekmartin/unicode-style#8]
hi, Unicode.Style is a great idea.
i'm wondering could you write down the algorythm of transform.js in pseudo code to ease the rewrite it in another language. unfortunately js is kind of obscure for me. my main goal to have an offline and headless tool to do the unicode style.
thanks for consideration.

**Comment by ekmartin** [comment]
Hi @bAndie91. I think the code block [here](https://github.com/ekmartin/unicode-style/blob/master/src/transform.js#L28-L58) explains it sort of well. The transformers consist of taking  either the first or the second part of the `modifier` variable (depending on whether it's lowercase or uppercase) and appending it to the existing character codepoint.

That part is shown here:
https://github.com/ekmartin/unicode-style/blob/2952f520a2c2811e3dac96946766e49802b0a9bc/src/transform.js#L159-L163

The `appenders` (e.g. underlining text) just append a unicode character to each character in the string:

https://github.com/ekmartin/unicode-style/blob/2952f520a2c2811e3dac96946766e49802b0a9bc/src/transform.js#L170-L182

**Comment by bAndie91** [comment]
i've ported unicode.style logic into cli in perl, see https://github.com/bAndie91/tools/blob/master/usr/bin/unicodestyle
